version: 0.4.{build}

platform:
  - x64

environment:
  NODE_ENV: production

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install

build_script:
  - yarn run webpack
  - yarn run dist

test: off
