version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - ps: Start-FileDownload 'https://s3.amazonaws.com/rebaslight/build/ffmpeg-bins-win.7z'
  - ps: 7z x ffmpeg-bins-win.7z
  - rename ffmpeg-bins-win ffmpeg-bins

build_script:
  - yarn run webpack
  - yarn run dist

test: off
